package com.example.demo.model;

import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a content object that can be persisted and retrieved.
 * Implements the IContent interface.
 */
@Document("Content")
public class Content implements IContent {
    /**
     * The unique autogenerated ID of the content object.
     */
    @Id
    private String contentID;
    /**
     * The Airtable ID associated with the content object.
     * Can be persisted.
     */
    @Field
    private String airtableID;
    /**
     * The hash of the json object.
     * Can be persisted.
     */
    @Field
    private String jsonHash;
    /**
     * The hash of binary data of the content.
     * Can be persisted.
     */
    @Field
    private String contentName;
    /**
     * The hash of binary data of the content.
     * Can be persisted.
     */
    @Field
    private List<String> binaryHashes;
    /**
     * The content JSON associated with the content object.
     * Not persisted.
     */
    @Transient
    private JSONObject contentJson;



    public Content() {

    }

    /**
     * Constructs a new Content object with the specified content hash, content JSON, and binary content.
     *
     * @param contentHash   The content hash of the Content object.
     * @param contentJson   The content JSON of the Content object.
     * @param binaryContent The binary content of the Content object.
     */
    public Content(String contentHash, JSONObject contentJson, byte[] binaryContent) {
        this.jsonHash = contentHash;
        this.contentJson = contentJson;
        this.binaryHashes = new ArrayList<>();
    }


    public String getContentID() {
        return contentID;
    }

    public void setContentID(String contentID) {
        this.contentID = contentID;
    }

    public String getAirtableID() {
        return airtableID;
    }


    public void setAirtableID(String airtableID) {
        this.airtableID = airtableID;
    }

    public String getJsonHash() {
        return jsonHash;
    }

    public void setJsonHash(String jsonHash) {
        this.jsonHash = jsonHash;
    }


    public JSONObject getContentJson() {
        return contentJson;
    }

    public void setContentJson(JSONObject contentJson) {
        this.contentJson = contentJson;
    }

    public String getContentName() {
        return contentName;
    }

    public void setContentName(String contentName) {
        this.contentName = contentName;
    }

    public List<String> getBinaryHashes() {
        return binaryHashes;
    }

    public void setBinaryHashes(List<String> binaryHashes) {
        this.binaryHashes = binaryHashes;
    }

    public void addBinaryHashToList(String binaryHash) {
        binaryHashes.add(binaryHash);
    }

    @Override
    public String toString() {
        return "Content{" +
                "contentID='" + contentID + '\'' +
                ", airtableID='" + airtableID + '\'' +
                ", jsonHash='" + jsonHash + '\'' +
                ", contentName='" + contentName + '\'' +
                ", binaryHashes=" + binaryHashes +
                ", contentJson=" + contentJson +
                '}';
    }
}
