package com.example.demo.model;

import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a content object that can be persisted and retrieved.
 * Implements the IContent interface.
 */
@Document("Content")
public class Content {
    /**
     * The unique autogenerated ID of the content object.
     */
    @Id
    private String contentID;
    /**
     * The Airtable ID associated with the content object.
     * Can be persisted.
     */
    @Field
    private String airtableID;
    /**
     * The hash of the json object.
     * Can be persisted.
     */
    @Field
    private String jsonHash;
    /**
     * The content name of the object.
     */
    @Field
    private String contentName;
    /**
     * The hash of binary data of the content.
     * Can be persisted.
     */
    @Field
    private List<String> binaryHashes;
    /**
     * The content JSON associated with the content object.
     * Not persisted.
     */
    @Transient
    private JSONObject contentJson;


    public Content() {
        this.binaryHashes = new ArrayList<>();
    }
    /**
     * Converts a Content object to a JSON object.
     *
     * @param content The Content object to be converted to a JSON object.
     * @return A JSON object representing the Content object.
     * @throws JSONException if there is an error while creating the JSON object.
     */
    public static JSONObject toJson(Content content) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("contentID", content.contentID);
        jsonObject.put("airtableID", content.airtableID);
        jsonObject.put("jsonHash", content.jsonHash);
        jsonObject.put("contentName", content.contentName);
        jsonObject.put("binaryHashes", content.binaryHashes);
        return jsonObject;
    }

    public String getAirtableID() {
        return airtableID;
    }

    public void setAirtableID(String airtableID) {
        this.airtableID = airtableID;
    }

    public String getJsonHash() {
        return jsonHash;
    }

    public void setJsonHash(String jsonHash) {
        this.jsonHash = jsonHash;
    }

    public List<String> getBinaryHashes() {
        return binaryHashes;
    }

    public void setBinaryHashes(List<String> binaryHashes) {
        this.binaryHashes = binaryHashes;
    }

    public void addBinaryHashToList(String binaryHash) {
        binaryHashes.add(binaryHash);
    }

    @Override
    public String toString() {
        return "Content{" +
                "contentID='" + contentID + '\'' +
                ", airtableID='" + airtableID + '\'' +
                ", jsonHash='" + jsonHash + '\'' +
                ", contentName='" + contentName + '\'' +
                ", binaryHashes=" + binaryHashes +
                ", contentJson=" + contentJson +
                '}';
    }
}
