package com.example.demo.model;

import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

@Document("Content")
public class Content implements IContent{
    //autoGenerated
    @Id
    private String contentID;
    //persisted
    @Field
    private String airtableID;
    //persisted
    @Field
    private String contentHash;
    //not persisted
    @Transient
    private JSONObject contentJson ;
    //not persisted
    @Transient
    private byte[] binaryContent;
    public Content() {

    }
    public Content(String contentHash, JSONObject contentJson, byte[] binaryContent) {
        this.contentHash = contentHash;
        this.contentJson = contentJson;
        this.binaryContent = binaryContent;
    }
    public static Content fromJson(String json) throws JSONException {
        JSONObject obj = null;
        try {
            obj = new JSONObject(json);
        } catch (JSONException e) {
            throw new RuntimeException(e);
        }
        //
        String contentHash = null;
        try {
            contentHash = obj.getString("contentHash");
        } catch (JSONException e) {
            throw new RuntimeException(e);
        }
        JSONObject contentJson = obj.getJSONObject("contentJson");
        byte[] binaryContent = new byte[0];
        Content content = new Content(contentHash, contentJson, binaryContent);
        String contentID = obj.optString("contentID");
        if (!contentID.isEmpty()) {
            content.setContentID(contentID);
        }
        String airtableID = obj.optString("airtableID");
        if (!airtableID.isEmpty()) {
            content.setAirtableID(airtableID);
        }
        return content;
    }
    public String getContentID() {
        return contentID;
    }

    public void setContentID(String contentID) {
        this.contentID = contentID;
    }

    public String getAirtableID() {
        return airtableID;
    }

    public void setAirtableID(String airtableID) {
        this.airtableID = airtableID;
    }

    public String getContentHash() {
        return contentHash;
    }

    public void setContentHash(String contentHash) {
        this.contentHash = contentHash;
    }

    public JSONObject getContentJson() {
        return contentJson;
    }

    public void setContentJson(JSONObject contentJson) {
        this.contentJson = contentJson;
    }

    public byte[] getBinaryContent() {
        return binaryContent;
    }

    public void setBinaryContent(byte[] binaryContent) {
        this.binaryContent = binaryContent;
    }
}
