version: '3'
services:
  mongodb:
    image: mongo
    networks:
      - my-network
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: DCP-Server
  server:
    build: .
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/DCP-Server
networks:
  my-network:

volumes:
  mongodb-data:
      driver: azure_file
      driver_opts:
        share_name: myshare
        storage_account_name: dcpcms
