version: '3'
services:
  mongodb:
    image: mongo
    networks:
      - my-network
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build: .
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/my-database

networks:
  my-network:

volumes:
  mongodb-data:
